name: Manually trigger an Azure Machine Learning job with inputs

on:
  workflow_dispatch:
    inputs:
      regularization_rate:
        description: 'Regularization rate'
        required: true
        default: 0.01 

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}


