name: automatically trigger an Azure Machine Learning job with inputs

on: 
  push:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group="dp100-main-demo"
        az configure --defaults workspace="training-ml104"
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml #--reg_rate ${{ github.event.inputs.reg_rate }}
    #- name: deploy to workspace
    #  run: |
    #    az ml online-endpoint create ...
    


